//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MusicPlayers struct {
	GuildID              string `sql:"primary_key"`
	State                []byte
	PlayingTrackUserData *string
	Type                 int64
	Queue                string
	LoopingType          int64
	History              string
	SkipVotes            string
}
