//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Tags struct {
	ID        int64 `sql:"primary_key"`
	GuildID   string
	OwnerID   string
	Name      string
	Content   string
	Uses      *int64
	CreatedAt time.Time
}
