//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PlayHistory = newPlayHistoryTable("public", "play_history", "")

type playHistoryTable struct {
	postgres.Table

	//Columns
	UserID     postgres.ColumnString
	Query      postgres.ColumnString
	Title      postgres.ColumnString
	LastUsedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PlayHistoryTable struct {
	playHistoryTable

	EXCLUDED playHistoryTable
}

// AS creates new PlayHistoryTable with assigned alias
func (a PlayHistoryTable) AS(alias string) *PlayHistoryTable {
	return newPlayHistoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PlayHistoryTable with assigned schema name
func (a PlayHistoryTable) FromSchema(schemaName string) *PlayHistoryTable {
	return newPlayHistoryTable(schemaName, a.TableName(), a.Alias())
}

func newPlayHistoryTable(schemaName, tableName, alias string) *PlayHistoryTable {
	return &PlayHistoryTable{
		playHistoryTable: newPlayHistoryTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newPlayHistoryTableImpl("", "excluded", ""),
	}
}

func newPlayHistoryTableImpl(schemaName, tableName, alias string) playHistoryTable {
	var (
		UserIDColumn     = postgres.StringColumn("user_id")
		QueryColumn      = postgres.StringColumn("query")
		TitleColumn      = postgres.StringColumn("title")
		LastUsedAtColumn = postgres.TimestampzColumn("last_used_at")
		allColumns       = postgres.ColumnList{UserIDColumn, QueryColumn, TitleColumn, LastUsedAtColumn}
		mutableColumns   = postgres.ColumnList{QueryColumn, LastUsedAtColumn}
	)

	return playHistoryTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:     UserIDColumn,
		Query:      QueryColumn,
		Title:      TitleColumn,
		LastUsedAt: LastUsedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
