//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PlayHistories struct {
	UserID     string `sql:"primary_key"`
	Query      string
	Title      string `sql:"primary_key"`
	LastUsedAt time.Time
}
