//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Tags struct {
	GuildID   string `sql:"primary_key"`
	OwnerID   string
	Name      string `sql:"primary_key"`
	Content   string
	Uses      int64
	CreatedAt time.Time
}
