//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LikedSong = newLikedSongTable("public", "liked_song", "")

type likedSongTable struct {
	postgres.Table

	//Columns
	UserID    postgres.ColumnString
	Query     postgres.ColumnString
	Title     postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type LikedSongTable struct {
	likedSongTable

	EXCLUDED likedSongTable
}

// AS creates new LikedSongTable with assigned alias
func (a LikedSongTable) AS(alias string) *LikedSongTable {
	return newLikedSongTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LikedSongTable with assigned schema name
func (a LikedSongTable) FromSchema(schemaName string) *LikedSongTable {
	return newLikedSongTable(schemaName, a.TableName(), a.Alias())
}

func newLikedSongTable(schemaName, tableName, alias string) *LikedSongTable {
	return &LikedSongTable{
		likedSongTable: newLikedSongTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newLikedSongTableImpl("", "excluded", ""),
	}
}

func newLikedSongTableImpl(schemaName, tableName, alias string) likedSongTable {
	var (
		UserIDColumn    = postgres.StringColumn("user_id")
		QueryColumn     = postgres.StringColumn("query")
		TitleColumn     = postgres.StringColumn("title")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		allColumns      = postgres.ColumnList{UserIDColumn, QueryColumn, TitleColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{QueryColumn, CreatedAtColumn}
	)

	return likedSongTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		Query:     QueryColumn,
		Title:     TitleColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
