//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Tags = newTagsTable("public", "tags", "")

type tagsTable struct {
	postgres.Table

	//Columns
	GuildID   postgres.ColumnString
	OwnerID   postgres.ColumnString
	Name      postgres.ColumnString
	Content   postgres.ColumnString
	Uses      postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TagsTable struct {
	tagsTable

	EXCLUDED tagsTable
}

// AS creates new TagsTable with assigned alias
func (a TagsTable) AS(alias string) *TagsTable {
	return newTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TagsTable with assigned schema name
func (a TagsTable) FromSchema(schemaName string) *TagsTable {
	return newTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TagsTable with assigned table prefix
func (a TagsTable) WithPrefix(prefix string) *TagsTable {
	return newTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TagsTable with assigned table suffix
func (a TagsTable) WithSuffix(suffix string) *TagsTable {
	return newTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTagsTable(schemaName, tableName, alias string) *TagsTable {
	return &TagsTable{
		tagsTable: newTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newTagsTableImpl("", "excluded", ""),
	}
}

func newTagsTableImpl(schemaName, tableName, alias string) tagsTable {
	var (
		GuildIDColumn   = postgres.StringColumn("guild_id")
		OwnerIDColumn   = postgres.StringColumn("owner_id")
		NameColumn      = postgres.StringColumn("name")
		ContentColumn   = postgres.StringColumn("content")
		UsesColumn      = postgres.IntegerColumn("uses")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		allColumns      = postgres.ColumnList{GuildIDColumn, OwnerIDColumn, NameColumn, ContentColumn, UsesColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{OwnerIDColumn, ContentColumn, UsesColumn, CreatedAtColumn}
	)

	return tagsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		GuildID:   GuildIDColumn,
		OwnerID:   OwnerIDColumn,
		Name:      NameColumn,
		Content:   ContentColumn,
		Uses:      UsesColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
