//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Voters = newVotersTable("public", "voters", "")

type votersTable struct {
	postgres.Table

	//Columns
	UserID    postgres.ColumnString
	ExpiresAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type VotersTable struct {
	votersTable

	EXCLUDED votersTable
}

// AS creates new VotersTable with assigned alias
func (a VotersTable) AS(alias string) *VotersTable {
	return newVotersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new VotersTable with assigned schema name
func (a VotersTable) FromSchema(schemaName string) *VotersTable {
	return newVotersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new VotersTable with assigned table prefix
func (a VotersTable) WithPrefix(prefix string) *VotersTable {
	return newVotersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new VotersTable with assigned table suffix
func (a VotersTable) WithSuffix(suffix string) *VotersTable {
	return newVotersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newVotersTable(schemaName, tableName, alias string) *VotersTable {
	return &VotersTable{
		votersTable: newVotersTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newVotersTableImpl("", "excluded", ""),
	}
}

func newVotersTableImpl(schemaName, tableName, alias string) votersTable {
	var (
		UserIDColumn    = postgres.StringColumn("user_id")
		ExpiresAtColumn = postgres.TimestampColumn("expires_at")
		allColumns      = postgres.ColumnList{UserIDColumn, ExpiresAtColumn}
		mutableColumns  = postgres.ColumnList{ExpiresAtColumn}
	)

	return votersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		ExpiresAt: ExpiresAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
